services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app                          # mount local code for hot-reload
    networks:
      - x-disturb
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
  
networks:
  x-disturb:
    driver: bridge
