services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8005:8000"
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - disturb-be-network
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped

networks:
  disturb-be-network:
    driver: bridge